### ISSUE TITLE
Artifact Bucket

### ISSUE THREAD

**Issue by mlkirkpatrick** [ndlib/ndlib-cdk#11]
It's such a small thing that it might seem silly, but we use it so frequently that it would let us collapse the rules into a single line implementation instead of copy+pasting the same chunk repeatedly. Even more important than simplifying code, it makes sure we conform to set standards during implementation, instead of needing to remember what to add each time.

**Current Implementations:**
https://github.com/ndlib/usurper-blueprints/blob/master/src/artifact-bucket.ts
https://github.com/ndlib/lambda-purl-blueprints/blob/master/deploy/lib/purl-pipeline-stack.ts#L149
https://github.com/ndlib/marble-blueprints/blob/master/deploy/cloudformation/manifest-pipeline-pipeline.yml
https://github.com/ndlib/library-research-award-blueprints/blob/master/lib/deployment-pipeline.ts#L40
https://github.com/ndlib/architecture_drawings_blueprints/blob/master/cdk/lib/cd-pipeline.ts#L37

**Comment by ialford** [comment]
@mlkirkpatrick I would be happy to work on this if no one else on the @ndlib/cdk-core team wants to take it.
